#goal definition
float64[4] target_pose
float64 radius
float64 z_level -74.0
int8 sides
float64 theta 0
float64 velocity_ratio 1.0
float64 acceleration_ratio 1.0
---
#result definition
float64[4] achieved_pose
---
#feedback definition
float64[4] current_pose